/* Automatically generated by './build/bin/build-entry.js' */

import aa from './aa/index.js';
import bb from './bb/index.js';

const components = [
  aa,
  bb
];

const install = function (Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.13.2',
  install,
  aa,
  bb
};
