/* Automatically generated by './build/bin/build-entry.js' */

import aaaa from './aaaa/index.js';
import bbbb from './bbbb/index.js';

const components = [
  aaaa,
  bbbb
];

const install = function (Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.13.2',
  install,
  aaaa,
  bbbb
};
